name: Game report
description: File a game report
title: "[CUSA00000]: Your PS4 Game Name"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
        ## Please, read the [README](/SysRay/psOff_compatibility/blob/main/README.md) before filing your issue.
  - type: textarea
    id: what-happened
    attributes:
      label: Please, describe what you get
      description: Is your game crashing, hangs or something else?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: Game version you are using
      description: You may leave this empty
      placeholder: v0.0
    validations:
      required: false
  - type: dropdown
    id: game-status
    attributes:
      label: Current game status
      default: 3
      options:
        - Playable
        - Ingame
        - Intro
        - Nothing
    validations:
      required: true
  - type: input
    id: emu-version
    attributes:
      label: Your emulator version
      description: |
        The current emulator version equals to the
        day archive got released. This field will be
        filled automatically if you use GameReport
        feature in psOff emulator.
      placeholder: '23 Sep 2024'
    validations:
      required: true
  - type: textarea
    id: log-area
    attributes:
      label: Upload your log there
      description: |
        Your emulator should generate logs in P7Logs folder, check it and upload the latest log there.
      placeholder: No logs :(
    validations:
      required: true
  - type: textarea
    id: screenshot-area
    attributes:
      label: Upload your screenshots there
      description: |
        You may take game's screenshots if you want. This is not necessary, but we would be grateful.
      placeholder: No screenshots :(
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Yes, I agree
      description: |
        By checking this, you confirm that your issue was created in accordance with all the rules, described in README.md
      options:
        - label: Yes, I read the rules and did everything according to them
          required: true
