name: Game report
description: File a game report
title: "[CUSA00000]: Your PS4 Game Name"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
        ## Please, read the [README](/SysRay/psOff_compatibility/blob/main/README.md) before filing your issue.
  - type: textarea
    id: what-happened
    attributes:
      label: Please, describe what you get
      description: Is your game crashing, hangs or something else?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: Game version you are using
      description: You may leave this empty
      placeholder: v0.0
    validations:
      required: false
  - type: dropdown
    id: game-status
    attributes:
      label: Current game status
      default: 3
      options:
        - Playable
        - Ingame
        - Intro
        - Nothing
    validations:
      required: true
  - type: input
    id: emu-version
    attributes:
      label: Your emulator version
      description: |
        It should be printed in your terminal every time
        you run the emulator. Type `psoff.exe --help`
        in your command prompt to check your current version.
        Or just take a look at the emulator's title bar.
      placeholder: 'v.0.5'
    validations:
      required: true
  - type: textarea
    id: log-area
    attributes:
      label: Upload your log there
      description: |
        Your emulator should generate logs in P7Logs folder, check it and upload the latest log there.
        If you don't have such folder, check you config/logging.json file,  the "sink" parameter
        should be equal to "FileBin". Before uploading it you should completely close your emulator!
      placeholder: No logs :(
    validations:
      required: true
  - type: textarea
    id: screenshot-area
    attributes:
      label: Upload your screenshots there
      description: You may take game's screenshots if you want. This is not necessary, but we would be grateful.
      placeholder: No screenshots :(
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Yes, I agree
      description: By checking this, you confirm that your issue was created in accordance with all the rules, described in README.md
      options:
        - label: Yes, I read the rules and did everything according to them
          required: true
